version: '2'
services:
  projetnetsuivi-app:
    image: projetnetsuivi
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://projetnetsuivi-postgresql:5432/ProjetNETSUIVI
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8077:8077
  projetnetsuivi-postgresql:
    extends:
      file: postgresql.yml
      service: projetnetsuivi-postgresql
